nome=("noboru")
sobrenome=("asato")
idade=(200)
ano_nascimento= (2023-idade)
maior_de_idade= (idade>=18)
altura_metros= (1.76)
print('nome:', nome)
print('SObrenome:', sobrenome)
print('Idade:', idade)
print('Ano de nascimento:', ano_nascimento)
print('É maior de idade?', maior_de_idade)
print('Altura em metros:', altura_metros)
idades=int(input("digite sua idade"))
print("sua idade é ",idades )